pokemon_dict = {
    "#001": {"nombre": "Bulbasaur", "tipos": ["Planta", "Veneno"]},
    "#002": {"nombre": "Ivysaur", "tipos": ["Planta", "Veneno"]},
    "#003": {"nombre": "Venusaur", "tipos": ["Planta", "Veneno"]},
    "#004": {"nombre": "Charmander", "tipos": ["Fuego"]},
    "#005": {"nombre": "Charmeleon", "tipos": ["Fuego"]},
    "#006": {"nombre": "Charizard", "tipos": ["Fuego", "Volador"]},
    "#007": {"nombre": "Squirtle", "tipos": ["Agua"]},
    "#008": {"nombre": "Wartortle", "tipos": ["Agua"]},
    "#009": {"nombre": "Blastoise", "tipos": ["Agua"]},
    "#010": {"nombre": "Caterpie", "tipos": ["Bicho"]},
    "#011": {"nombre": "Metapod", "tipos": ["Bicho"]},
    "#012": {"nombre": "Butterfree", "tipos": ["Bicho", "Volador"]},
    "#013": {"nombre": "Weedle", "tipos": ["Bicho", "Veneno"]},
    "#014": {"nombre": "Kakuna", "tipos": ["Bicho", "Veneno"]},
    "#015": {"nombre": "Beedrill", "tipos": ["Bicho", "Veneno"]},
    "#016": {"nombre": "Pidgey", "tipos": ["Normal", "Volador"]},
    "#017": {"nombre": "Pidgeotto", "tipos": ["Normal", "Volador"]},
    "#018": {"nombre": "Pidgeot", "tipos": ["Normal", "Volador"]},
    "#019": {"nombre": "Rattata", "tipos": ["Normal"]},
    "#020": {"nombre": "Raticate", "tipos": ["Normal"]},
    "#021": {"nombre": "Spearow", "tipos": ["Normal", "Volador"]},
    "#022": {"nombre": "Fearow", "tipos": ["Normal", "Volador"]},
    "#023": {"nombre": "Ekans", "tipos": ["Veneno"]},
    "#024": {"nombre": "Arbok", "tipos": ["Veneno"]},
    "#025": {"nombre": "Pikachu", "tipos": ["Eléctrico"]},
    "#026": {"nombre": "Raichu", "tipos": ["Eléctrico"]},
    "#027": {"nombre": "Sandshrew", "tipos": ["Tierra"]},
    "#028": {"nombre": "Sandslash", "tipos": ["Tierra"]},
    "#029": {"nombre": "Nidoran♀", "tipos": ["Veneno"]},
    "#030": {"nombre": "Nidorina", "tipos": ["Veneno"]},
    "#031": {"nombre": "Nidoqueen", "tipos": ["Veneno", "Tierra"]},
    "#032": {"nombre": "Nidoran♂", "tipos": ["Veneno"]},
    "#033": {"nombre": "Nidorino", "tipos": ["Veneno"]},
    "#034": {"nombre": "Nidoking", "tipos": ["Veneno", "Tierra"]},
    "#035": {"nombre": "Clefairy", "tipos": ["Hada"]},
    "#036": {"nombre": "Clefable", "tipos": ["Hada"]},
    "#037": {"nombre": "Vulpix", "tipos": ["Fuego"]},
    "#038": {"nombre": "Ninetales", "tipos": ["Fuego"]},
    "#039": {"nombre": "Jigglypuff", "tipos": ["Normal", "Hada"]},
    "#040": {"nombre": "Wigglytuff", "tipos": ["Normal", "Hada"]},
    "#041": {"nombre": "Zubat", "tipos": ["Veneno", "Volador"]},
    "#042": {"nombre": "Golbat", "tipos": ["Veneno", "Volador"]},
    "#043": {"nombre": "Oddish", "tipos": ["Planta", "Veneno"]},
    "#044": {"nombre": "Gloom", "tipos": ["Planta", "Veneno"]},
    "#045": {"nombre": "Vileplume", "tipos": ["Planta", "Veneno"]},
    "#046": {"nombre": "Paras", "tipos": ["Bicho", "Planta"]},
    "#047": {"nombre": "Parasect", "tipos": ["Bicho", "Planta"]},
    "#048": {"nombre": "Venonat", "tipos": ["Bicho", "Veneno"]},
    "#049": {"nombre": "Venomoth", "tipos": ["Bicho", "Veneno"]},
    "#050": {"nombre": "Diglett", "tipos": ["Tierra"]},
    "#051": {"nombre": "Dugtrio", "tipos": ["Tierra"]},
    "#052": {"nombre": "Meowth", "tipos": ["Normal"]},
    "#053": {"nombre": "Persian", "tipos": ["Normal"]},
    "#054": {"nombre": "Psyduck", "tipos": ["Agua"]},
    "#055": {"nombre": "Golduck", "tipos": ["Agua"]},
    "#056": {"nombre": "Mankey", "tipos": ["Lucha"]},
    "#057": {"nombre": "Primeape", "tipos": ["Lucha"]},
    "#058": {"nombre": "Growlithe", "tipos": ["Fuego"]},
    "#059": {"nombre": "Arcanine", "tipos": ["Fuego"]},
    "#060": {"nombre": "Poliwag", "tipos": ["Agua"]},
    "#061": {"nombre": "Poliwhirl", "tipos": ["Agua"]},
    "#062": {"nombre": "Poliwrath", "tipos": ["Agua", "Lucha"]},
    "#063": {"nombre": "Abra", "tipos": ["Psíquico"]},
    "#064": {"nombre": "Kadabra", "tipos": ["Psíquico"]},
    "#065": {"nombre": "Alakazam", "tipos": ["Psíquico"]},
    "#066": {"nombre": "Machop", "tipos": ["Lucha"]},
    "#067": {"nombre": "Machoke", "tipos": ["Lucha"]},
    "#068": {"nombre": "Machamp", "tipos": ["Lucha"]},
    "#069": {"nombre": "Bellsprout", "tipos": ["Planta", "Veneno"]},
    "#070": {"nombre": "Weepinbell", "tipos": ["Planta", "Veneno"]},
    "#071": {"nombre": "Victreebel", "tipos": ["Planta", "Veneno"]},
    "#072": {"nombre": "Tentacool", "tipos": ["Agua", "Veneno"]},
    "#073": {"nombre": "Tentacruel", "tipos": ["Agua", "Veneno"]},
    "#074": {"nombre": "Geodude", "tipos": ["Roca", "Tierra"]},
    "#075": {"nombre": "Graveler", "tipos": ["Roca", "Tierra"]},
    "#076": {"nombre": "Golem", "tipos": ["Roca", "Tierra"]},
    "#077": {"nombre": "Ponyta", "tipos": ["Fuego"]},
    "#078": {"nombre": "Rapidash", "tipos": ["Fuego"]},
    "#079": {"nombre": "Slowpoke", "tipos": ["Agua", "Psíquico"]},
    "#080": {"nombre": "Slowbro", "tipos": ["Agua", "Psíquico"]},
    "#081": {"nombre": "Magnemite", "tipos": ["Eléctrico", "Acero"]},
    "#082": {"nombre": "Magneton", "tipos": ["Eléctrico", "Acero"]},
    "#083": {"nombre": "Farfetch'd", "tipos": ["Normal", "Volador"]},
    "#084": {"nombre": "Doduo", "tipos": ["Normal", "Volador"]},
    "#085": {"nombre": "Dodrio", "tipos": ["Normal", "Volador"]},
    "#086": {"nombre": "Seel", "tipos": ["Agua"]},
    "#087": {"nombre": "Dewgong", "tipos": ["Agua", "Hielo"]},
    "#088": {"nombre": "Grimer", "tipos": ["Veneno"]},
    "#089": {"nombre": "Muk", "tipos": ["Veneno"]},
    "#090": {"nombre": "Shellder", "tipos": ["Agua"]},
    "#091": {"nombre": "Cloyster", "tipos": ["Agua", "Hielo"]},
    "#092": {"nombre": "Gastly", "tipos": ["Fantasma", "Veneno"]},
    "#093": {"nombre": "Haunter", "tipos": ["Fantasma", "Veneno"]},
    "#094": {"nombre": "Gengar", "tipos": ["Fantasma", "Veneno"]},
    "#095": {"nombre": "Onix", "tipos": ["Roca", "Tierra"]},
    "#096": {"nombre": "Drowzee", "tipos": ["Psíquico"]},
    "#097": {"nombre": "Hypno", "tipos": ["Psíquico"]},
    "#098": {"nombre": "Krabby", "tipos": ["Agua"]},
    "#099": {"nombre": "Kingler", "tipos": ["Agua"]},
    "#100": {"nombre": "Voltorb", "tipos": ["Eléctrico"]},
    "#101": {"nombre": "Electrode", "tipos": ["Eléctrico"]},
    "#102": {"nombre": "Exeggcute", "tipos": ["Planta", "Psíquico"]},
    "#103": {"nombre": "Exeggutor", "tipos": ["Planta", "Psíquico"]},
    "#104": {"nombre": "Cubone", "tipos": ["Tierra"]},
    "#105": {"nombre": "Marowak", "tipos": ["Tierra"]},
    "#106": {"nombre": "Hitmonlee", "tipos": ["Lucha"]},
    "#107": {"nombre": "Hitmonchan", "tipos": ["Lucha"]},
    "#108": {"nombre": "Lickitung", "tipos": ["Normal"]},
    "#109": {"nombre": "Koffing", "tipos": ["Veneno"]},
    "#110": {"nombre": "Weezing", "tipos": ["Veneno"]},
    "#111": {"nombre": "Rhyhorn", "tipos": ["Tierra", "Roca"]},
    "#112": {"nombre": "Rhydon", "tipos": ["Tierra", "Roca"]},
    "#113": {"nombre": "Chansey", "tipos": ["Normal"]},
    "#114": {"nombre": "Tangela", "tipos": ["Planta"]},
    "#115": {"nombre": "Kangaskhan", "tipos": ["Normal"]},
    "#116": {"nombre": "Horsea", "tipos": ["Agua"]},
    "#117": {"nombre": "Seadra", "tipos": ["Agua"]},
    "#118": {"nombre": "Goldeen", "tipos": ["Agua"]},
    "#119": {"nombre": "Seaking", "tipos": ["Agua"]},
    "#120": {"nombre": "Staryu", "tipos": ["Agua"]},
    "#121": {"nombre": "Starmie", "tipos": ["Agua", "Psíquico"]},
    "#122": {"nombre": "Mr. Mime", "tipos": ["Psíquico", "Hada"]},
    "#123": {"nombre": "Scyther", "tipos": ["Bicho", "Volador"]},
    "#124": {"nombre": "Jynx", "tipos": ["Hielo", "Psíquico"]},
    "#125": {"nombre": "Electabuzz", "tipos": ["Eléctrico"]},
    "#126": {"nombre": "Magmar", "tipos": ["Fuego"]},
    "#127": {"nombre": "Pinsir", "tipos": ["Bicho"]},
    "#128": {"nombre": "Tauros", "tipos": ["Normal"]},
    "#129": {"nombre": "Magikarp", "tipos": ["Agua"]},
    "#130": {"nombre": "Gyarados", "tipos": ["Agua", "Volador"]},
    "#131": {"nombre": "Lapras", "tipos": ["Agua", "Hielo"]},
    "#132": {"nombre": "Ditto", "tipos": ["Normal"]},
    "#133": {"nombre": "Eevee", "tipos": ["Normal"]},
    "#134": {"nombre": "Vaporeon", "tipos": ["Agua"]},
    "#135": {"nombre": "Jolteon", "tipos": ["Eléctrico"]},
    "#136": {"nombre": "Flareon", "tipos": ["Fuego"]},
    "#137": {"nombre": "Porygon", "tipos": ["Normal"]},
    "#138": {"nombre": "Omanyte", "tipos": ["Roca", "Agua"]},
    "#139": {"nombre": "Omastar", "tipos": ["Roca", "Agua"]},
    "#140": {"nombre": "Kabuto", "tipos": ["Roca", "Agua"]},
    "#141": {"nombre": "Kabutops", "tipos": ["Roca", "Agua"]},
    "#142": {"nombre": "Aerodactyl", "tipos": ["Roca", "Volador"]},
    "#143": {"nombre": "Snorlax", "tipos": ["Normal"]},
    "#144": {"nombre": "Articuno", "tipos": ["Hielo", "Volador"]},
    "#145": {"nombre": "Zapdos", "tipos": ["Eléctrico", "Volador"]},
    "#146": {"nombre": "Moltres", "tipos": ["Fuego", "Volador"]},
    "#147": {"nombre": "Dratini", "tipos": ["Dragón"]},
    "#148": {"nombre": "Dragonair", "tipos": ["Dragón"]},
    "#149": {"nombre": "Dragonite", "tipos": ["Dragón", "Volador"]},
    "#150": {"nombre": "Mewtwo", "tipos": ["Psíquico"]},
    "#151": {"nombre": "Mew", "tipos": ["Psíquico"]}
}