ataques = {
    "Placaje": {"nombre": "Placaje", 
             "tipo": "Normal",
             "poder": 35,
             "precision": 95,
             "pp": 35,
             },
    "Gruñido": {"nombre": "Gruñido", 
             "tipo": "Normal",
             "poder": 0,
             "precision": 100,
             "pp": 40,
             },
    "Arañazo": {"nombre": "Arañazo", 
             "tipo": "Normal",
             "poder": 40,
             "precision": 100,
             "pp": 35,
             }
}